# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 02:45
from __future__ import unicode_literals
from random import choice

from django.db import migrations


ICONS = [
    'bug',
    'bus',
    'beer',
    'compass',
    'gamepad',
    'language',
    'leaf',
    'shopping-basket',
    'sitemap',
    'support',
    'bitcoin',
    'dollar',
    'ship',
    'rocket',
    'sliders',
    'shield',
    'university'
]
APP_DATA = [
    {
        'name': 'App1',
        'description': 'Application 1',
        'color': 'Red',
        'default_status': True,
        'icon': choice(ICONS)
    },
    {
        'name': 'App2',
        'description': 'Application 2',
        'color': 'Blue',
        'default_status': False,
        'icon': choice(ICONS)
    },
    {
        'name': 'App3',
        'description': 'Application 3',
        'color': 'Yellow',
        'default_status': True,
        'icon': choice(ICONS)
    },
    {
        'name': 'App4',
        'description': 'Application 4',
        'color': 'Green',
        'default_status': False,
        'icon': choice(ICONS)
    },
    {
        'name': 'App5',
        'description': 'Application 5',
        'color': 'Purple',
        'default_status': False,
        'icon': choice(ICONS)
    }
]


def make_apps(apps, schema_editor, app_data=APP_DATA):
    App = apps.get_model('aliapp', 'App')
    for data in app_data:
        app = App(**data)
        app.save()


class Migration(migrations.Migration):
    dependencies = [
        ('aliapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(make_apps),
    ]
