# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 16:29
from __future__ import unicode_literals
from datetime import datetime

from django.db import migrations
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password


# From the instructions, "We are not worried about security right now."
USERS = [
    {
        'username': 'user1',
        # Never do this in public
        'password': make_password('glbrcpass'),
        'last_login': datetime.now()
    },
    {
        'username': 'user2',
        # Never do this in public
        'password': make_password('glbrcpass'),
        'last_login': datetime.now()
    },
    {
        'username': 'user3',
        # Never do this in public
        'password': make_password('glbrcpass'),
        'last_login': datetime.now()
    }
]


def make_users(apps, schema_editor, users=USERS):
    for user in users:
        new_user = User(**user)
        new_user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('aliapp', '0005_auto_20160724_2056'),
    ]

    operations = [
        migrations.RunPython(make_users),
    ]
